### ISSUE TITLE
Yolov3 INT8 quantization tftrt

### ISSUE THREAD

**Issue by kingardor** [whitelok/tensorrt-int8-python-sample#1]
Hi. I'm looking to convert  yolov3 to int8 trt model. I have been successful inGP16 but need help with the calibration step for INT8.

**Comment by whitelok** [comment]
Could you paste the error message here? Thanks.

**Comment by kingardor** [comment]
Hi. Thanks for the prompt reply. I figured it out. I just used the documentation from TensorFlow TensorRT to do it.
Thanks :)
